services:
  chocobot:
    build: .
    container_name: chocobot_discord_community_assistant
    restart: unless-stopped
    environment:
      - COMMAND_PREFIX=!
      - VISIBLE_PLAYLIST_QUEUE_LENGTH=6
    networks:
      - main
    env_file:
      - ./.env
    depends_on:
      - lavalink
  lavalink:
    # pin the image version to Lavalink v4
    image: ghcr.io/lavalink-devs/lavalink:latest
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=${LAVALINK_SERVER_PORT}
    env_file:
      - ./.env
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins
    networks:
      - main
    ports:
      - "${LAVALINK_SERVER_PORT}:${LAVALINK_SERVER_PORT}"

networks:
  main: